### ISSUE TITLE
Daemon doesnt start on custom build of snap

### ISSUE THREAD

**Issue by ToxicHelix** [canonical/ubuntu-frame-vnc#29]
I have attemped to build the ubtunu-frame-vnc snap locally from source as I want to add additional parameters to the wayvnc command line.

As an initial test I downloaded the core20 and core22 branches and then built the unmodified code, the only change being the snap name in the snapcrafy.yaml file.

However whenever I start the daemon it errors with the below:

ERROR: ../src/src/main.c: 408: Virtual Pointer protocol not supported by compositor.
ERROR: ../src/src/main.c: 409: wayvnc may still work if started with --disable-input.
ERROR: ../src/src/main.c: 1391: Failed to initialise wayland

The snap from the Snap store is fine.

I have checked all the plugs are connected per the original snap and there is no difference.

The snap logs on ubuntu-frame do not show any connection attempt or log line when the custom ubuntu-frame-vnc snap attempts to start. 

I did try setting the authorise-without-apparmor flags in ubuntu-frame but this didn't work either.

**Comment by Saviq** [comment]
Hi @ToxicHelix, that's because Frame explicitly only allows the upstream snap name:

https://github.com/canonical/ubuntu-frame/blob/e74ef963c397224a0ffd02c98fb9967017d079c4/src/frame_authorization.cpp#L31-L35

You could open it up through the `add-wayland-extensions` option (see [the config docs](https://mir-server.io/docs/ubuntu-frame-configuration-options#heading--snap-configuration-config), but the disadvantage there is that it's a blanket allow then.

We do have ideas to [open this up](https://github.com/canonical/ubuntu-frame/issues/201) (e.g. have a `screencast` snap interface), but not currently roadmapped.

Any case, not a problem with this particular snap, so I'm going to close.

**Comment by ToxicHelix** [comment]
Thank you. Sorry I was unable to respond as my account was locked. Thank you for the feedback. I was able to get this to work with the extension.

Is this documented anywhere that this needs to be done when forking the snap code? It is not obvious that there is a dependancy on the setting in the ubuntu-frame itself and the vnc snap. 

I agree however that using a slot/plug would be more secure, aswell as self documenting.

Having said that the reason for this approach was driven because of issue #28. If we can work around that I would no longer need build a custom copy.
